### ISSUE TITLE
Depreciation Modules break typescript type imports

### ISSUE THREAD

**Issue by AWare** [fastify/deprecate-modules#2]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

na

### Plugin version

na

### Node.js version

na

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

na

### Description

The deprecation modules do not appear to forward types and only forward the old modules, this caused typescript to not be able to pick up the new types.

### Steps to Reproduce

- Install any of the migrated modules from before the migration, 
- import and use its type,
- compile with tsc
- update module
- recompile

### Expected Behavior

Modules type signature will not change on a minor semver change.

**Comment by jsumners** [comment]
Use the new scoped module.
